In [1]:
# ! pip install datasets transformers rouge-score nltk

In [18]:
# from huggingface_hub import notebook_login

# notebook_login()

In [19]:
# !git lfs install

In [1]:
import transformers

print(transformers.__version__)

4.17.0


In [2]:
model_checkpoint = "t5-small"

In [3]:
from datasets import load_dataset, load_metric

raw_datasets = load_dataset("xsum")
metric = load_metric("rouge")

Using custom data configuration default
Reusing dataset xsum (C:\Users\mishr\.cache\huggingface\datasets\xsum\default\1.2.0\32c23220eadddb1149b16ed2e9430a05293768cfffbdfd151058697d4c11f934)
100%|██████████| 3/3 [00:00<00:00, 80.06it/s]


In [4]:
raw_datasets

DatasetDict({
    train: Dataset({
        features: ['document', 'summary', 'id'],
        num_rows: 204045
    })
    validation: Dataset({
        features: ['document', 'summary', 'id'],
        num_rows: 11332
    })
    test: Dataset({
        features: ['document', 'summary', 'id'],
        num_rows: 11334
    })
})

In [5]:
from transformers import AutoTokenizer
    
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

In [6]:
if model_checkpoint in ["t5-small", "t5-base", "t5-larg", "t5-3b", "t5-11b"]:
    prefix = "summarize: "
else:
    prefix = ""

In [7]:
max_input_length = 1024
max_target_length = 128

def preprocess_function(examples):
    inputs = [prefix + doc for doc in examples["document"]]
    model_inputs = tokenizer(inputs, max_length=max_input_length, truncation=True)

    # Setup the tokenizer for targets
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(examples["summary"], max_length=max_target_length, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [8]:
tokenized_datasets = raw_datasets.map(preprocess_function, batched=True)

Loading cached processed dataset at C:\Users\mishr\.cache\huggingface\datasets\xsum\default\1.2.0\32c23220eadddb1149b16ed2e9430a05293768cfffbdfd151058697d4c11f934\cache-3b5f22899b7915a3.arrow
Loading cached processed dataset at C:\Users\mishr\.cache\huggingface\datasets\xsum\default\1.2.0\32c23220eadddb1149b16ed2e9430a05293768cfffbdfd151058697d4c11f934\cache-8ff3375eef38f280.arrow
Loading cached processed dataset at C:\Users\mishr\.cache\huggingface\datasets\xsum\default\1.2.0\32c23220eadddb1149b16ed2e9430a05293768cfffbdfd151058697d4c11f934\cache-802327cc9600dbf6.arrow


In [9]:
from transformers import AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainingArguments, Seq2SeqTrainer

model = AutoModelForSeq2SeqLM.from_pretrained(model_checkpoint)

In [10]:
batch_size = 4
model_name = model_checkpoint.split("/")[-1]
args = Seq2SeqTrainingArguments(
    f"{model_name}-finetuned-xsum",
    evaluation_strategy = "epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=1,
    predict_with_generate=True,
    fp16=True,
    # push_to_hub=True,
)

In [11]:
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

In [65]:
import nltk
import numpy as np

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    # Replace -100 in the labels as we can't decode them.
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    
    # Rouge expects a newline after each sentence
    decoded_preds = ["\n".join(nltk.sent_tokenize(pred.strip())) for pred in decoded_preds]
    decoded_labels = ["\n".join(nltk.sent_tokenize(label.strip())) for label in decoded_labels]
    
    result = metric.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    # Extract a few results
    result = {key: value.mid.fmeasure * 100 for key, value in result.items()}
    
    # Add mean generated length
    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in predictions]
    result["gen_len"] = np.mean(prediction_lens)
    
    return {k: round(v, 4) for k, v in result.items()}

In [13]:
trainer = Seq2SeqTrainer(
    model,
    args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

Using amp half precision backend


In [21]:
# trainer.train()

In [16]:
trainer.push_to_hub()

In [17]:
model

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dro

In [20]:
trainer.eval_dataset

Dataset({
    features: ['document', 'summary', 'id', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 11332
})

In [22]:
predictions = trainer.predict(tokenized_datasets["validation"])

The following columns in the test set  don't have a corresponding argument in `T5ForConditionalGeneration.forward` and have been ignored: id, document, summary. If id, document, summary are not expected by `T5ForConditionalGeneration.forward`,  you can safely ignore this message.
***** Running Prediction *****
  Num examples = 11332
  Batch size = 4
100%|██████████| 2833/2833 [09:29<00:00,  5.56it/s]

In [55]:
predictions

PredictionOutput(predictions=array([[    0,  2759, 10740, ...,  7904,    29,  2600],
       [    0,  4551,     7, ...,    16,     8,   166],
       [    0,    37,   146, ..., 24051, 18137,     5],
       ...,
       [    0,    37,   837, ...,  4807,  4807,   313],
       [    0,  3746,  2384, ...,  1535,     8,   804],
       [    0,  2846,    49, ...,  4843,  1162,   121]], dtype=int64), label_ids=array([[18263,  6552,  3815, ...,  -100,  -100,  -100],
       [ 4551,     7,   994, ...,  -100,  -100,  -100],
       [   37,   970,  2951, ...,  -100,  -100,  -100],
       ...,
       [   37,   837,  1775, ...,  -100,  -100,  -100],
       [ 7190,    31,     7, ...,  -100,  -100,  -100],
       [   37,  1323,    13, ...,  -100,  -100,  -100]], dtype=int64), metrics={'test_loss': 2.4194087982177734, 'test_rouge1': 29.0994, 'test_rouge2': 8.2844, 'test_rougeL': 22.9664, 'test_rougeLsum': 22.9694, 'test_gen_len': 18.8035, 'test_runtime': 582.7195, 'test_samples_per_second': 19.447, 'test_ste

In [23]:
print(predictions.predictions.shape, predictions.label_ids.shape)

(11332, 20) (11332, 128)


In [31]:
import numpy as np

preds = np.argmax(predictions.predictions)

In [35]:
predictions.predictions[0]

array([    0,  2759, 10740,    43,   118,  4977,    28,     3,     9,
         939,    13, 10883,  2319,     3,  8321,    12,     8,  7904,
          29,  2600], dtype=int64)

In [30]:
predictions.label_ids[0]

array([18263,  6552,  3815,  3370,    49,  3084,   264,    26,  1924,
          65,  4283,    16,  1614,  5815,   386, 10740, 11970,    13,
        7813,  7712,     5,     1,  -100,  -100,  -100,  -100,  -100,
        -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
        -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
        -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
        -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
        -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
        -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
        -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
        -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
        -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
        -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
        -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
        -100,  -100]

In [41]:
tokenized_datasets["validation"]['document'][0]

'The ex-Reading defender denied fraudulent trading charges relating to the Sodje Sports Foundation - a charity to raise money for Nigerian sport.\nMr Sodje, 37, is jointly charged with elder brothers Efe, 44, Bright, 50 and Stephen, 42.\nAppearing at the Old Bailey earlier, all four denied the offence.\nThe charge relates to offences which allegedly took place between 2008 and 2014.\nSam, from Kent, Efe and Bright, of Greater Manchester, and Stephen, from Bexley, are due to stand trial in July.\nThey were all released on bail.'

In [42]:
tokenized_datasets["validation"]['summary'][0]

'Former Premier League footballer Sam Sodje has appeared in court alongside three brothers accused of charity fraud.'

In [45]:
import torch

In [50]:
inputs = tokenizer('The ex-Reading defender denied fraudulent trading charges relating to the Sodje Sports Foundation - a charity to raise money for Nigerian sport.\nMr Sodje, 37, is jointly charged with elder brothers Efe, 44, Bright, 50 and Stephen, 42.\nAppearing at the Old Bailey earlier, all four denied the offence.\nThe charge relates to offences which allegedly took place between 2008 and 2014.\nSam, from Kent, Efe and Bright, of Greater Manchester, and Stephen, from Bexley, are due to stand trial in July.\nThey were all released on bail.', return_tensors="pt")
labels = torch.tensor([1]).unsqueeze(0).cuda()  # Batch size 1
# labels = labels.device('cuda')
outputs = model(**inputs, labels=labels)

AttributeError: 

In [51]:


text = "My friends are cool but they eat too many carbs."
inputs = tokenizer(text, max_length=1024, return_tensors="np")
encoder_outputs = model.encode(**inputs)

decoder_start_token_id = model.config.decoder_start_token_id
decoder_input_ids = torch.ones((inputs.input_ids.shape[0], 1), dtype="i4") * decoder_start_token_id

outputs = model.decode(decoder_input_ids, encoder_outputs)
logits = outputs.logits

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


AttributeError: 'T5ForConditionalGeneration' object has no attribute 'encode'

In [44]:
predictions[0]

array([[    0,  2759, 10740, ...,  7904,    29,  2600],
       [    0,  4551,     7, ...,    16,     8,   166],
       [    0,    37,   146, ..., 24051, 18137,     5],
       ...,
       [    0,    37,   837, ...,  4807,  4807,   313],
       [    0,  3746,  2384, ...,  1535,     8,   804],
       [    0,  2846,    49, ...,  4843,  1162,   121]], dtype=int64)

In [64]:
import nltk
import numpy as np

def compute_metrics_changed(predictions, labels):
    predictions, labels = predictions, labels
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    # Replace -100 in the labels as we can't decode them.
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    
    # Rouge expects a newline after each sentence
    decoded_preds = ["\n".join(nltk.sent_tokenize(pred.strip())) for pred in decoded_preds]
    decoded_labels = ["\n".join(nltk.sent_tokenize(label.strip())) for label in decoded_labels]
    

    
    return decoded_preds, decoded_labels


In [66]:
d_preds, d_labels = compute_metrics_changed(predictions.predictions, predictions.label_ids)

In [68]:
d_preds[0]

'Two brothers have been charged with a series of offences relating to the Nigerian sport'

In [70]:
d_labels[0]

'Former Premier League footballer Sam Sodje has appeared in court alongside three brothers accused of charity fraud.'